version: "3"

networks:
  subquery-net:
    driver: bridge

volumes:
  subquery_ipfs_data:
  subquery_ipfs_export:
  subquery_database:

services:
  ipfs:
    container_name: ipfs-subquery
    image: ipfs/kubo:master-latest
    restart: unless-stopped
    ports:
      - "5001:5001"
      - "5002:8080"
    volumes:
      - subquery_ipfs_data:/data/ipfs
      - subquery_ipfs_export:/export
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5001"]
      interval: 30s
      timeout: 10s
      retries: 15
    networks:
      - subquery-net

  postgres:
    container_name: postgres-subquery
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    restart: unless-stopped
    ports:
      - "5433:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d subquery-project -U subquery-user"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - subquery_database:/var/lib/postgresql/data
    networks:
      - subquery-net
